# Site settings
title: Dr Neville Grech
email: me@nevillegrech.com
description: > # this means to ignore newlines until "baseurl:"
  Personal web site for Neville Grech.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.nevillegrech.com" # the base hostname & protocol for your site
linkedin_username: nevillegrech
skype_username: nevillegrech
github_username:  nevillegrech
twitter_username: neville_grech

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
